version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_queue
    ports:
      - "6379:6379"
    networks:
      - forecast-net

  bot_service:
    build: ./bot_service
    container_name: telegram_bot
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./bot_service/logs:/app/logs
    networks:
      - forecast-net

  analysis_service:
    build: ./analysis_service
    container_name: analysis_worker
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./analysis_service/logs:/app/logs
    networks:
      - forecast-net

networks:
  forecast-net:
    driver: bridge
